Repository godot-rust/book, pull requests merged in 2022-03, with the labels that each got.

#62 FAQ: bindgen C headers not found
  src/faq/configuration.md
  src/getting-started/setup.md
Labels: faq

#65 Updated setup.md
  src/getting-started/setup.md
Labels: outdated-api

#64 0.10.0 Migration Guide
  src/SUMMARY.md
  src/advanced-guides/migrating-0-8.md
  src/advanced-guides/migrating-0-9.md
Labels: new-topic
