Repository godot-rust/book, pull requests merged in 2023-12, with the labels that each got.

#16 Update `Gd::with_base` method recommendation to `Gd::from_init_fn`
  src/intro/objects.md
Labels: outdated

#15 Web exports guide
  .github/other/.markdownlint.jsonc
  src/SUMMARY.md
  src/index.md
  src/toolchain/export-web.md
  src/toolchain/images/web-browser-run.png
  src/toolchain/images/web-export.png
Labels: new-topic

#18 Add copyright notice
  .github/other/licenserc.yml
  .github/workflows/cd.yml
  book.toml
  lint.sh
  src/SUMMARY.md
  src/contribute/conventions.md
  src/contribute/dev-tools.md
  src/contribute/index.md
  src/index.md
  src/intro/hello-world.md
  src/intro/index.md
  src/intro/objects.md
  src/intro/setup.md
  src/toolchain/compatibility.md
  src/toolchain/debugging.md
  src/toolchain/export-web.md
  src/toolchain/godot-version.md
  src/toolchain/index.md
Labels: tooling

#19 Include oxipng in CI
  .github/workflows/cd.yml
Labels: tooling
