Repository godot-rust/book, pull requests merged in 2024-02, with the labels that each got.

#31 singleton unregister fix + refcounted
  src/recipes/engine-singleton.md
Labels: error

#32 Be more specific about the reader needs to do
  src/intro/hello-world.md
Labels: enhancement

#33 Add reloadable option to hello-world gdextension file
  src/intro/hello-world.md
Labels: enhancement

#34 add required attribute to editor-plugin tutorial
  src/recipes/editor-plugin.md
Labels: error

#35 Chapter about virtual script functions
  src/SUMMARY.md
  src/register/virtual-functions.md
Labels: new-topic
