Repository godot-rust/book, pull requests merged in 2024-01, with the labels that each got.

#20 Add instructions to use Cargo to set GODOT4_BIN to relative path.
  src/toolchain/godot-version.md
Labels: new-topic

#21 Update `base` composition with `base()`, `base_mut()` methods.
  src/intro/hello-world.md
  src/intro/objects.md
Labels: outdated-api

#25 fix borrow of angular_speed
  src/intro/hello-world.md
Labels: bug

#26 Registration of classes, functions, properties and more
  ReadMe.md
  src/SUMMARY.md
  src/intro/hello-world.md
  src/register/classes.md
  src/register/constants.md
  src/register/functions.md
  src/register/index.md
  src/register/properties.md
  src/register/signals.md
Labels: new-topic

#23 Tools Recipes
  .gitignore
  src/SUMMARY.md
  src/recipes/custom-icons.md
  src/recipes/custom-resources.md
  src/recipes/editor-plugin.md
  src/recipes/engine-singleton.md
  src/recipes/index.md
Labels: new-topic
