Repository godot-rust/book, pull requests merged in 2024-12, with the labels that each got.

#62 Update string argument passing documentation
  src/godot-api/functions.md
  src/intro/hello-world.md
  src/recipes/editor-plugin/inspector-plugins.md
Labels: outdated-api

#64 Update to examples that use Strings for passing arguments.
  src/godot-api/builtins.md
  src/migrate/index.md
  src/recipes/editor-plugin/inspector-plugins.md
  src/recipes/engine-singleton.md
Labels: outdated-api

#63 Add missing rustflags for exporting to web
  src/toolchain/export-web.md
Labels: error

#66 Add a point in the Hello World troubleshooting docs
  src/intro/hello-world.md
Labels: enhancement

#67 Ecosystem page
  config/.markdownlint.jsonc
  src/SUMMARY.md
  src/ecosystem/index.md
Labels: new-topic
