Repository godot-rust/book, pull requests merged in 2024-06, with the labels that each got.

#46 Update tutorial for selecting Godot versions
  src/godot-api/builtins.md
  src/godot-api/functions.md
  src/intro/hello-world.md
  src/intro/setup.md
  src/recipes/engine-singleton.md
  src/toolchain/godot-version.md
Labels: enhancement

#49 Update CI versions
  .github/workflows/cd.yml
Labels: tooling

#48 Added recipe for Inspector Plugin
  src/SUMMARY.md
  src/recipes/editor-plugin/images/after.png
  src/recipes/editor-plugin/images/before.png
  src/recipes/editor-plugin/index.md
  src/recipes/editor-plugin/inspector-plugins.md
Labels: new-topic

#42 First draft of android readme
  src/SUMMARY.md
  src/toolchain/export-android.md
Labels: new-topic
