Repository godot-rust/book, pull requests merged in 2025-02, with the labels that each got.

#72 Minor typo in prelude description
  src/intro/hello-world.md
Labels: enhancement

#73 Replaces deprecated #[init(default = ...)] with #[init(val = ...)]
  src/register/constructors.md
Labels: outdated-api

#74 Update web export instructions for Godot 4.3+
  src/toolchain/export-web.md
  src/toolchain/images/web-export.png
Labels: enhancement

#76 :art: Theme
  .github/other/licenserc.yml
  book.toml
  config/mdbook-admonish.css
  config/tomorrow-noon.css
  src/register/classes.md
  src/register/properties.md
  src/register/virtual-functions.md
  src/toolchain/debugging.md
  src/toolchain/export-mac-and-ios.md
  theme/ThemeNotes.md
  theme/book.js
  theme/css/variables.css
  theme/highlight.css
  theme/index.hbs
  theme/tomorrow-night.css
Labels: tooling

#77 Add information for `#[class(tool)]` in custom resource
  src/recipes/custom-resources.md
Labels: enhancement

#78 Add links to Simplified Chinese book + demos
  src/index.md
Labels: enhancement
