Repository godot-rust/book, pull requests merged in 2025-03, with the labels that each got.

#81 Fix: replace outdated info
  src/recipes/custom-resources.md
  src/toolchain/compatibility.md
Labels: outdated-api, enhancement

#82 Fix link from constructors page to objects page
  src/register/constructors.md
Labels: error

#84 Wasm docs threading fixes and common errors
  src/toolchain/export-web.md
Labels: enhancement

#86 Removing deprecated editor_plugin attribute key
  src/recipes/editor-plugin/index.md
  src/recipes/editor-plugin/inspector-plugins.md
Labels: outdated-api

#87 Type-safe signals
  config/mdbook-admonish.css
  src/register/signals.md
Labels: new-topic

#89 Add "delete cache" to troubleshoot section in hello-world.md
  src/intro/hello-world.md
Labels: enhancement

#88 Adjust target feature instructions for Wasm threading
  src/toolchain/export-web.md
Labels: enhancement
